CHARMAP "A", $bb
CHARMAP "B", $bc
CHARMAP "C", $bd
CHARMAP "D", $be
CHARMAP "E", $bf
CHARMAP "F", $c0
CHARMAP "G", $c1
CHARMAP "H", $c2
CHARMAP "I", $c3
CHARMAP "J", $c4
CHARMAP "K", $c5
CHARMAP "L", $c6
CHARMAP "M", $c7
CHARMAP "N", $c8
CHARMAP "O", $c9
CHARMAP "P", $ca
CHARMAP "Q", $cb
CHARMAP "R", $cc
CHARMAP "S", $cd
CHARMAP "T", $ce
CHARMAP "U", $cf
CHARMAP "V", $d0
CHARMAP "W", $d1
CHARMAP "X", $d2
CHARMAP "Y", $d3
CHARMAP "Z", $d4
CHARMAP " ", $d5
CHARMAP "a", $d6
CHARMAP "b", $d7
CHARMAP "c", $d8
CHARMAP "d", $d9
CHARMAP "e", $da
CHARMAP "f", $db
CHARMAP "g", $dc
CHARMAP "h", $dd
CHARMAP "i", $de
CHARMAP "j", $df
CHARMAP "k", $e0
CHARMAP "l", $e1
CHARMAP "m", $e2
CHARMAP "n", $e3
CHARMAP "o", $e4
CHARMAP "p", $e5
CHARMAP "q", $e6
CHARMAP "r", $e7
CHARMAP "s", $e8
CHARMAP "t", $e9
CHARMAP "u", $ea
CHARMAP "v", $eb
CHARMAP "w", $ec
CHARMAP "x", $ed
CHARMAP "y", $ee
CHARMAP "z", $ef
CHARMAP "0", $f0
CHARMAP "1", $f1
CHARMAP "2", $f2
CHARMAP "3", $f3
CHARMAP "4", $f4
CHARMAP "5", $cd
CHARMAP "6", $f5
CHARMAP "7", $f6
CHARMAP "8", $f7
CHARMAP "9", $f8
CHARMAP "!", $f0
CHARMAP "?", $fa
CHARMAP "-", $fb
CHARMAP "'", $fc
CHARMAP ".", $fd
CHARMAP ",", $fe
CHARMAP ":", $ff
